language: java
jdk:
    - openjdk11

addons:
    sonarcloud:
        organization: "letisia-ornelle"
        token: "ad4823cedb238ce3606c039cfa887c133cd54a29"
        
       
script:
- ant build
- sonar-scanner